Udpate pywikibot hash in Pipfile.lock
pywikibot was bumped in 907c6fee, but the hash was left the same.

Since then running pipenv install fails with:
```
Collecting pywikibot==3.0.20200703
  Using cached pywikibot-3.0.20200703.tar.gz (515 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE.
If you have updated the package versions, please update the hashes.
    pywikibot==3.0.20200703 from
 https://files.pythonhosted.org/packages/<snip>/pywikibot-3.0.20200703.tar.gz
Expected sha256
5cd191c509af78698bef3d5bb444780d5be63deb8c811ea6028290994c9c9b90
     Got
af7dc748b8b1d73e00f27058820df888bc40542d1a44809ef1a43d4747676e47
ERROR: Couldn't install package: pywikibot
```

Change-Id: I7624ecfce763f22789f11bd3c84e0693fa790d23