Open a database connection for each dataset during harvesting
Harvesting currently opens a database connection at the
very beginning, and expects it to stay open during the
entire harvesting (several hours).

This leads to harvesting failing because the connection is gone [1]

Here we instead open the connection for one dataset,
close it, and open a new one for the next dataset.

[1] Example error:
```
ERROR: Traceback (most recent call last):
...
ERROR: Unknown error occurred when processing country pl in lang pl
(2013, 'Lost connection to MySQL server during query
([Errno 104] Connection reset by peer)')
```

Change-Id: Iaafe842dabc2a917923c05c801b0ff9cde248afe