Validate the monuments_config.schema is a schema
`check-jsonschema` can validate a schema against the metaschema it
refered to by "$schema" by using `--check-metaschema`. It ensures the
schema is indeed a valid schema.

Example output for an invalid schema:

  $ tox -e jsonschema
  jsonschema: commands[0]> .jsonschema_cmd.sh
  Validating schema ./erfgoedbot/monuments_config/monuments_config.schema
  Schema validation errors were encountered.
    erfgoedbot/monuments_config/monuments_config.schema::$.properties.lang.type:
    'strazeing' is not valid under any of the given schemas
    Underlying errors caused this.
    Best Match:
      $.properties.lang.type: 'strazeing' is not one of ['array',
      'boolean', 'integer', 'null', 'number', 'object', 'string']
  ERROR: Invalid schema file: ./erfgoedbot/monuments_config/monuments_config.schema
  jsonschema: exit 1 (0.20 seconds) ./labs/tools/heritage> .jsonschema_cmd.sh pid=1509573

For a valid schema:

  $ tox -e jsonschema
  jsonschema: commands[0]> .jsonschema_cmd.sh
  Validating schema ./erfgoedbot/monuments_config/monuments_config.schema
  ok -- validation done

  Processing json configs in ./erfgoedbot/monuments_config
  ok -- validation done
  √ ./erfgoedbot/monuments_config/ch_it.json
  ok -- validation done
  √ ./erfgoedbot/monuments_config/ve_es.json
  ok -- validation done

Change-Id: I9289f6d4f588e0c67755d8604825bbc898aea8a7