Skip SPARQL type in missing_commonscat_links.py
This script was crashing when processing nl-wd with:
```
  File "missing_commonscat_links.py", line 115, in lookupSourceField
    for field in countryconfig.get('fields'):
TypeError: 'NoneType' object is not iterable
```
because SPARQL sources do not use fields.

This script is not meant to be used for SPARQL sources,
we just skip them silently.

Bug: T175899
Change-Id: I5b968f8c9ad4beabf3d76ed339e4b018ff14bded