Use `revisions` instead of `getLatestEditors` in check_emailable_users
Notifying the user was failing with
```
ERROR: Error when notifying user [[commons:User:XYZ]], skipping
'Page' object has no attribute 'getLatestEditors'
```

The method `getLatestEditors` was removed in Pywikibot 6.2.0 [1],
and we upgrade from 3.0 to 6.6.2 in c43703e411.

[1] https://doc.wikimedia.org/pywikibot/stable/changelog.html#id17
```
BasePage.getLatestEditors() method was removed in favour of contributors() or revisions()
```

Bug: T317279
Change-Id: Ic6bc57c321f04a2179c7dc27b7e306d6da168efd