Catch `PageSaveRelatedError` in save_to_wiki_or_local
Besides `OtherPageSaveError`, `PageSaveRelatedError`
can also occur when saving a page on a wiki.

This happens in particular when hitting an AbuseFilter.
For example:
```
ERROR: editpage: abusefilter-disallowed
Hit AbuseFilter: حمله شخصی,

```

That exception is now also caught in `save_to_wiki_or_local`.

It used to be caught in `update_database` while processing
`unknownFieldsStatistics`, which is now unnecessary since
it ultimately calls `save_to_wiki_or_local`.

Bug: T176530
Change-Id: I22a2d41beb74d437241616cc61e2a33d2039a37c